COGNITIVE_OPERATIONS = [
    "Temporal Reasoning: Analyze sequences and predict temporal trends.",
    "Spatial Reasoning: Understand and manipulate spatial relationships.",
    "Multi-modal Integration: Synthesize information from different sensory channels.",
    "Abductive Reasoning: Infer the best explanation from incomplete evidence.",
    "Causal Inference: Determine cause-effect relationships.",
    "Quantitative Estimation: Approximate numerical values from qualitative data.",
    "Analogical Mapping: Align similarities between seemingly different domains.",
    "Pattern Generalization: Extend specific patterns to general rules.",
    "Contradiction Resolution: Identify and resolve conflicting information.",
    "Divergent Exploration: Explore a broad range of possibilities.",
    "Convergent Refinement: Narrow down options to the most viable ones.",
    "Hypothetical Modeling: Construct theoretical models of scenarios.",
    "Scenario Simulation: Run mental simulations to predict outcomes.",
    "Hierarchical Structuring: Organize concepts into layered hierarchies.",
    "Contextual Flexibility: Adjust understanding based on new contextual cues.",
    "Concept Isolation: Separate individual ideas from intertwined data.",
    "Meta-Reasoning: Reflect on the reasoning process itself.",
    "Information Synthesis: Merge disparate pieces of information into cohesive wholes.",
    "Data Extrapolation: Extend known data to predict unknown outcomes.",
    "Logical Sequencing: Order reasoning steps in a coherent progression.",
    "Semantic Differentiation: Distinguish subtle differences in meaning.",
    "Pragmatic Reasoning: Evaluate the practical implications of decisions.",
    "Ambiguity Resolution: Clarify ambiguous or vague data points.",
    "Conflict Analysis: Identify and analyze conflicting components.",
    "Decision Weighing: Evaluate pros and cons of alternative solutions.",
    "Deductive Reasoning: Apply general principles to reach specific conclusions.",
    "Inductive Reasoning: Derive general rules from specific observations.",
    "Feedback Loop Integration: Incorporate iterative feedback into reasoning.",
    "Adaptive Problem-Solving: Adjust strategies dynamically as situations evolve.",
    "Error Correction: Detect and fix reasoning errors.",
    "Semantic Annotation: Label and organize semantic elements.",
    "Prototyping Ideas: Create rough conceptual models for testing.",
    "Uncertainty Management: Evaluate and mitigate uncertain factors.",
    "Cognitive Load Balancing: Distribute processing resources efficiently.",
    "Data Prioritization: Rank information by relevance.",
    "Knowledge Abstraction: Convert detailed data into abstract concepts.",
    "Hypothesis Prioritization: Rank hypotheses based on plausibility.",
    "Analogical Extension: Extend analogies to new contexts.",
    "Contextual Reinterpretation: Revise interpretations when context shifts.",
    "Multivariate Analysis: Assess relationships among multiple variables.",
    "Semantic Recombination: Merge separate semantic elements into new structures.",
    "Deductive Consolidation: Combine multiple deductions into a unified conclusion.",
    "Logical Validation: Rigorously test logical consistency.",
    "Cognitive Integration: Combine separate cognitive functions into coherent processes.",
    "Data Pattern Extraction: Isolate recurring data patterns.",
    "Problem Recontextualization: Reframe problems in alternative contexts.",
    "Relevancy Filtering: Discard irrelevant information.",
    "Evidence Weighing: Assess the strength of supporting evidence.",
    "Perspective Taking: Consider different viewpoints.",
    "Alternative Scenario Generation: Develop multiple potential future scenarios.",
    "Interdisciplinary Synthesis: Merge concepts from diverse fields.",
    "Conceptual Reiteration: Reword ideas to reveal hidden nuances.",
    "Structural Mapping: Identify the underlying structure of complex data.",
    "Relational Inference: Deduce relationships between variables.",
    "Probabilistic Forecasting: Predict outcomes based on probability distributions.",
    "Cognitive Partitioning: Divide complex tasks into manageable segments.",
    "Semantic Contrast: Compare and contrast meanings effectively.",
    "Dynamic Reassessment: Continuously re-evaluate solutions as new information emerges.",
    "Heuristic Application: Use heuristics to simplify decision making.",
    "Cognitive Restructuring: Reorganize mental frameworks to better solve problems.",
    "Strategic Abstraction: Identify strategic high-level patterns.",
    "Systematic Decomposition: Methodically break down complex systems.",
    "Micro-analysis: Examine fine details within a larger context.",
    "Macro-analysis: Evaluate overall system-level dynamics.",
    "Linguistic Parsing: Analyze linguistic structure and syntax.",
    "Information Chunking: Group related pieces of data together.",
    "Unification: Merge disparate ideas into a unified theory.",
    "Probabilistic Integration: Merge probabilistic data from multiple sources.",
    "Logical Inference: Draw conclusions from logical premises.",
    "Conceptual Refinement: Sharpen and improve conceptual definitions.",
    "Data Normalization: Standardize data for effective analysis.",
    "Pattern Synthesis: Combine patterns to form a new comprehensive pattern.",
    "Consistency Checking: Validate that all parts of reasoning align.",
    "Operational Mapping: Connect abstract concepts to actionable steps.",
    "Computational Simulation: Run internal simulations to test ideas.",
    "Intuitive Judgment: Rely on instinctive evaluations when data is scarce.",
    "Critical Decomposition: Critically assess and dismantle ideas.",
    "Idea Consolidation: Merge similar ideas to reduce complexity.",
    "Dynamic Modeling: Create models that can change with input data.",
    "Relationship Scaling: Evaluate how relationships change in different scales.",
    "Hypothesis Cross-Validation: Test multiple hypotheses concurrently.",
    "Conceptual Expansion: Widen the scope of existing concepts.",
    "Analytical Abstraction: Draw high-level insights from detailed analysis.",
    "Feedback Synthesis: Integrate feedback into a revised solution.",
    "Discrepancy Analysis: Identify differences between expected and actual outcomes.",
    "Semantic Interpolation: Fill gaps in semantic knowledge using surrounding context.",
    "Intent Extraction: Deduce underlying intents in communication.",
    "Inferential Bridging: Connect indirect inferences to form a coherent picture.",
    "Data Fusion: Merge multiple data sources into a single coherent dataset.",
    "Cognitive Simulation: Simulate various cognitive processes to test strategies.",
    "Context-Driven Modification: Adjust approaches based on contextual cues.",
    "Variable Prioritization: Rank variables by their impact on the outcome.",
    "Temporal Extrapolation: Forecast future events based on historical data.",
    "Cross-Domain Reasoning: Apply insights from one domain to another.",
    "Model Calibration: Fine-tune internal models to match real-world data.",
    "Strategic Forecasting: Predict strategic outcomes in complex scenarios.",
    "Interdependent Reasoning: Evaluate systems where components affect each other.",
    "Adaptive Scaling: Adjust cognitive strategies based on problem scale.",
    "Logical Structuring: Build logical frameworks for organizing ideas.",
    "Iterative Optimization: Continuously refine solutions through repeated cycles."
]

BASE_PROMPT = """You are a language model implementing cognitive operations.
Forget all previous interactions. You do NOT remember past prompts or solutions.
When you get a problem, choose five steps for reasoning:

1. Abstraction: Extract key elements of the problem.
2. Goal Alignment: Define the target and constraints.
3. Creative Thinking: Generate possible solution approaches.
4. Resolving Inconsistencies: Verify and refine the solution.
5. Summarizing: Provide a concise, step-by-step solution.

Now, solve the following problem:
"""